import { useEffect, useRef, useState } from 'react'
import sizes from './assets/gallery/sizes.json'

// The web-sized images are generated by scripts/build-gallery.py, which also
// writes sizes.json. Each photo has a full-size file for the lightbox and a
// `-thumb` one for the grid.
const files = import.meta.glob('./assets/gallery/*.webp', {
  eager: true,
  query: '?url',
  import: 'default',
})

const INSTAGRAM_POST_URL = 'https://www.instagram.com/p/Dd7ykeMlRht/'

// Figures from the iGEM Toronto recap post.
const stats = [
  { value: '200+', label: 'people registered' },
  { value: '15', label: 'posters presented' },
  { value: '5', label: 'speakers and panellists' },
]

// The 13 photos from the recap post, in the order they were posted. Shown first.
// TO CHANGE THE PHOTOS: edit PHOTOS in scripts/build-gallery.py, re-run it, then
// match the slugs here. `alt` doubles as the caption in the lightbox.
const highlights = [
  { slug: 'highlight-01', alt: 'The opening slide on the lecture hall screen: University of Toronto Microplastics Conference, September 19.' },
  { slug: 'highlight-02', alt: 'A speaker at the lectern during a talk.' },
  { slug: 'highlight-03', alt: 'A student presenter explaining a poster on plastic-degrading enzymes to two attendees.' },
  { slug: 'highlight-04', alt: 'iGEM Toronto team members at the front of the hall during their presentation.' },
  { slug: 'highlight-05', alt: 'A speaker at the podium, looking up at the audience.' },
  { slug: 'highlight-06', alt: 'Attendees chatting over coffee during the poster session.' },
  { slug: 'highlight-07', alt: 'The iGEM Toronto team gathered for a group photo at the front of the lecture hall.' },
  { slug: 'highlight-08', alt: 'Thanking the sponsors, with the Longo’s, Jukebox, Fraser River Junk Removal and U of T Trash Team logos on screen.' },
  { slug: 'highlight-09', alt: 'The iGEM Toronto skyline emblem printed on the back of a team sweater.' },
  { slug: 'highlight-10', alt: 'The U of T Trash Team panel, with their Urban Litter Challenge on screen.' },
  { slug: 'highlight-11', alt: 'The regulatory panel in discussion, with the moderator seated to the left.' },
  { slug: 'highlight-12', alt: 'Madeleine Milne presenting on microplastics and human health.' },
  { slug: 'highlight-13', alt: 'Organisers taking a selfie-stick photo with the whole audience.' },
]

const morePhotos = [
  { slug: 'talk-ecological-impacts', alt: 'Dr. Chelsea Rochman’s talk on the ecological impacts of plastic pollution.' },
  { slug: 'audience', alt: 'Audience members listening during a talk.' },
  { slug: 'igem-team-presenting', alt: 'The iGEM Toronto team lined up at the front of the hall to present their project.' },
  { slug: 'at-the-podium', alt: 'A presenter speaking into a microphone at the podium.' },
  { slug: 'student-panel', alt: 'Three student panellists at the front table, one answering a question.' },
  { slug: 'trash-team-group', alt: 'Six members of the U of T Trash Team posing together.' },
  { slug: 'panellist-speaking', alt: 'A panellist making a point during the regulatory panel.' },
  { slug: 'panellists', alt: 'Two panellists sharing a laugh mid-answer.' },
  { slug: 'panel-moderator', alt: 'The panel moderator, microphone in hand.' },
  { slug: 'audience-question', alt: 'An audience member asking the panel a question.' },
  { slug: 'speaker-gifts', alt: 'Four of the speakers and panellists with their thank-you gifts.' },
  { slug: 'poster-session-atrium', alt: 'Attendees reading posters in the Bahen Centre atrium.' },
  { slug: 'poster-session-browsing', alt: 'The poster session in full swing along the atrium wall.' },
  { slug: 'poster-session-discussion', alt: 'A poster presenter in conversation with attendees.' },
  { slug: 'poster-presenter', alt: 'A student presenter beside a poster on nearshore microplastic hotspots.' },
  { slug: 'poster-session-attendees', alt: 'Two attendees with coffee at the poster session.' },
  { slug: 'sticker-table', alt: 'iGEM Toronto bottle stickers laid out for sale.' },
  { slug: 'crowd', alt: 'The audience sharing a laugh between sessions.' },
  { slug: 'organisers', alt: 'Four of the organisers in the lecture hall.' },
  { slug: 'everyone', alt: 'Speakers, organisers and attendees gathered in the lecture hall for a group photo.' },
].map((photo) => ({ ...photo, ...resolve(photo.slug) }))

const featured = highlights.map((photo) => ({ ...photo, ...resolve(photo.slug) }))

// One list for the lightbox, so previous/next runs straight through both sets.
const allPhotos = [...featured, ...morePhotos]

function resolve(slug) {
  const [width, height] = sizes[slug]
  return {
    full: files[`./assets/gallery/${slug}.webp`],
    thumb: files[`./assets/gallery/${slug}-thumb.webp`],
    width,
    height,
  }
}

function Chevron({ direction }) {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true">
      <path d={direction === 'previous' ? 'M15 5l-7 7 7 7' : 'M9 5l7 7-7 7'} />
    </svg>
  )
}

function GalleryLightbox({ index, setIndex }) {
  const closeButtonRef = useRef(null)
  const dialogRef = useRef(null)
  const photo = allPhotos[index]

  // Runs once per open: `index` changes as the visitor pages through, and
  // re-running this would hand focus back to the page between photos.
  useEffect(() => {
    const previouslyFocused = document.activeElement
    const previousOverflow = document.body.style.overflow
    document.body.style.overflow = 'hidden'
    closeButtonRef.current?.focus()

    return () => {
      document.body.style.overflow = previousOverflow
      previouslyFocused?.focus()
    }
  }, [])

  useEffect(() => {
    const step = (delta) =>
      setIndex((current) => (current + delta + allPhotos.length) % allPhotos.length)

    const handleKeyDown = (event) => {
      if (event.key === 'Escape') setIndex(null)
      if (event.key === 'ArrowLeft') step(-1)
      if (event.key === 'ArrowRight') step(1)
      if (event.key !== 'Tab') return

      const focusable = dialogRef.current?.querySelectorAll('button:not([disabled])')
      if (!focusable?.length) return
      const first = focusable[0]
      const last = focusable[focusable.length - 1]

      if (event.shiftKey && document.activeElement === first) {
        event.preventDefault()
        last.focus()
      } else if (!event.shiftKey && document.activeElement === last) {
        event.preventDefault()
        first.focus()
      }
    }

    window.addEventListener('keydown', handleKeyDown)
    return () => window.removeEventListener('keydown', handleKeyDown)
  }, [setIndex])

  const step = (delta) => setIndex((index + delta + allPhotos.length) % allPhotos.length)

  return (
    <div
      className="gallery-lightbox-backdrop"
      onMouseDown={(event) => {
        if (event.target === event.currentTarget) setIndex(null)
      }}
    >
      <section
        className="gallery-lightbox"
        ref={dialogRef}
        role="dialog"
        aria-modal="true"
        aria-label="Conference photo viewer"
      >
        <button
          className="gallery-lightbox-button gallery-lightbox-close"
          onClick={() => setIndex(null)}
          ref={closeButtonRef}
          type="button"
          aria-label="Close photo viewer"
        >
          <span aria-hidden="true">×</span>
        </button>

        <button
          className="gallery-lightbox-button gallery-lightbox-previous"
          onClick={() => step(-1)}
          type="button"
          aria-label="Previous photo"
        >
          <Chevron direction="previous" />
        </button>

        <figure className="gallery-lightbox-figure">
          {/* Keyed so the previous photo is dropped at once, rather than
              lingering until the next one has loaded. */}
          <img
            key={photo.slug}
            src={photo.full}
            alt={photo.alt}
            width={photo.width}
            height={photo.height}
          />
          <figcaption aria-live="polite">
            <span>{photo.alt}</span>
            <span className="gallery-lightbox-count">
              {index + 1} / {allPhotos.length}
            </span>
          </figcaption>
        </figure>

        <button
          className="gallery-lightbox-button gallery-lightbox-next"
          onClick={() => step(1)}
          type="button"
          aria-label="Next photo"
        >
          <Chevron direction="next" />
        </button>
      </section>
    </div>
  )
}

function GalleryTile({ photo, onOpen, sizes: sizesAttr }) {
  return (
    <button
      className="gallery-tile"
      onClick={onOpen}
      style={{ '--ratio': photo.width / photo.height }}
      type="button"
    >
      <img
        src={photo.thumb}
        srcSet={`${photo.thumb} 800w, ${photo.full} 1800w`}
        sizes={sizesAttr}
        alt={photo.alt}
        width={photo.width}
        height={photo.height}
        loading="lazy"
        decoding="async"
      />
    </button>
  )
}

export default function Gallery() {
  const [openIndex, setOpenIndex] = useState(null)

  return (
    <section className="gallery" id="gallery" aria-labelledby="gallery-title">
      <div className="section-heading">
        <div>
          <p className="section-label">September 19, 2026 · That’s a wrap</p>
          <h2 id="gallery-title">The day in photos</h2>
        </div>
        <p className="gallery-intro">
          A full day of talks, a keynote, a panel and a student poster session, bringing
          together people who care about one of the most pressing environmental issues out
          there. Thank you to everyone who came.
        </p>
      </div>

      <dl className="gallery-stats">
        {stats.map((stat) => (
          <div key={stat.label}>
            <dt>{stat.label}</dt>
            <dd>{stat.value}</dd>
          </div>
        ))}
      </dl>

      <ul className="gallery-highlights" aria-label="Highlights from the conference">
        {featured.map((photo, index) => (
          <li key={photo.slug}>
            <GalleryTile
              photo={photo}
              onOpen={() => setOpenIndex(index)}
              sizes={
                index === 0
                  ? '(max-width: 800px) 100vw, 45vw'
                  : '(max-width: 800px) 50vw, 22vw'
              }
            />
          </li>
        ))}
      </ul>

      <div className="gallery-more-heading">
        <h3 id="gallery-more-title">More from the day</h3>
        <a className="text-link" href={INSTAGRAM_POST_URL} target="_blank" rel="noopener noreferrer">
          See the recap on Instagram
          <svg viewBox="0 0 24 24" aria-hidden="true">
            <path d="M5 12h14M13 6l6 6-6 6" />
          </svg>
        </a>
      </div>

      <ul className="gallery-more" aria-labelledby="gallery-more-title">
        {morePhotos.map((photo, index) => (
          <li key={photo.slug} style={{ '--ratio': photo.width / photo.height }}>
            <GalleryTile
              photo={photo}
              onOpen={() => setOpenIndex(featured.length + index)}
              sizes="(max-width: 800px) 50vw, 25vw"
            />
          </li>
        ))}
      </ul>

      {openIndex !== null && <GalleryLightbox index={openIndex} setIndex={setOpenIndex} />}
    </section>
  )
}
